import { Product, Order } from './types';

export const categories = [
  { id: 'electronics', name: 'Electronics', icon: '💻', count: 6 },
  { id: 'clothing', name: 'Clothing', icon: '👕', count: 5 },
  { id: 'home', name: 'Home & Garden', icon: '🏠', count: 4 },
  { id: 'sports', name: 'Sports', icon: '⚽', count: 4 },
  { id: 'books', name: 'Books', icon: '📚', count: 3 },
  { id: 'beauty', name: 'Beauty', icon: '✨', count: 3 },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'Experience crystal-clear audio with our premium noise-cancelling wireless headphones. Features 40-hour battery life, premium comfort padding, and advanced Bluetooth 5.3 connectivity. Perfect for music lovers and professionals alike.',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.8,
    reviews: 2341,
    inStock: true,
    featured: true,
    tags: ['wireless', 'noise-cancelling', 'bluetooth'],
  },
  {
    id: '2',
    name: 'Smart Watch Ultra',
    description: 'Stay connected and track your fitness with the Smart Watch Ultra. Features include heart rate monitoring, GPS tracking, water resistance up to 100m, and a stunning AMOLED display.',
    price: 449.99,
    originalPrice: 549.99,
    image: 'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.7,
    reviews: 1856,
    inStock: true,
    featured: true,
    tags: ['smartwatch', 'fitness', 'gps'],
  },
  {
    id: '3',
    name: 'Mechanical Keyboard RGB',
    description: 'Professional-grade mechanical keyboard with customizable RGB lighting, Cherry MX switches, and aircraft-grade aluminum construction. N-key rollover and programmable macros.',
    price: 179.99,
    originalPrice: 219.99,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.9,
    reviews: 3102,
    inStock: true,
    featured: true,
    tags: ['mechanical', 'rgb', 'gaming'],
  },
  {
    id: '4',
    name: 'Ultra-Slim Laptop 15"',
    description: 'Powerful yet lightweight laptop featuring the latest processor, 16GB RAM, 512GB SSD, and a stunning 4K display. Perfect for work and creative projects.',
    price: 1299.99,
    originalPrice: 1499.99,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.6,
    reviews: 987,
    inStock: true,
    tags: ['laptop', '4k', 'ultraslim'],
  },
  {
    id: '5',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices. Features smart temperature control and foreign object detection.',
    price: 39.99,
    originalPrice: 59.99,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.4,
    reviews: 2156,
    inStock: true,
    tags: ['wireless', 'charging', 'qi'],
  },
  {
    id: '6',
    name: 'Bluetooth Speaker Portable',
    description: 'Powerful portable speaker with 360° sound, waterproof design (IPX7), and 24-hour battery life. Perfect for outdoor adventures.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.5,
    reviews: 1432,
    inStock: true,
    tags: ['bluetooth', 'portable', 'waterproof'],
  },
  {
    id: '7',
    name: 'Classic Denim Jacket',
    description: 'Timeless denim jacket crafted from premium Japanese selvedge denim. Features a comfortable fit with vintage-inspired wash.',
    price: 129.99,
    originalPrice: 169.99,
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500&h=500&fit=crop',
    category: 'clothing',
    rating: 4.6,
    reviews: 876,
    inStock: true,
    featured: true,
    tags: ['denim', 'classic', 'jacket'],
  },
  {
    id: '8',
    name: 'Premium Cotton T-Shirt',
    description: 'Ultra-soft Pima cotton t-shirt with a modern fit. Pre-shrunk and color-fast for lasting comfort and style.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    category: 'clothing',
    rating: 4.3,
    reviews: 3456,
    inStock: true,
    tags: ['cotton', 'casual', 'tshirt'],
  },
  {
    id: '9',
    name: 'Running Sneakers Pro',
    description: 'Engineered for performance with responsive cushioning, breathable mesh upper, and durable rubber outsole. Ideal for daily training.',
    price: 159.99,
    originalPrice: 189.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    category: 'clothing',
    rating: 4.7,
    reviews: 2134,
    inStock: true,
    tags: ['running', 'sneakers', 'athletic'],
  },
  {
    id: '10',
    name: 'Wool Blend Overcoat',
    description: 'Sophisticated overcoat in premium wool blend. Features a tailored silhouette with notch lapels and a two-button closure.',
    price: 299.99,
    originalPrice: 449.99,
    image: 'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=500&h=500&fit=crop',
    category: 'clothing',
    rating: 4.8,
    reviews: 654,
    inStock: true,
    tags: ['wool', 'overcoat', 'formal'],
  },
  {
    id: '11',
    name: 'Casual Chino Pants',
    description: 'Versatile chino pants with a comfortable stretch fit. Perfect for both office and weekend wear.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&h=500&fit=crop',
    category: 'clothing',
    rating: 4.4,
    reviews: 1789,
    inStock: true,
    tags: ['chino', 'casual', 'pants'],
  },
  {
    id: '12',
    name: 'Smart Home Hub',
    description: 'Central control for your smart home. Compatible with 1000+ devices, features voice control, and automated routines.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=500&h=500&fit=crop',
    category: 'home',
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    tags: ['smart-home', 'hub', 'automation'],
  },
  {
    id: '13',
    name: 'Ergonomic Office Chair',
    description: 'Premium ergonomic chair with adjustable lumbar support, breathable mesh back, and 4D armrests. Built for all-day comfort.',
    price: 549.99,
    originalPrice: 699.99,
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500&h=500&fit=crop',
    category: 'home',
    rating: 4.8,
    reviews: 2567,
    inStock: true,
    featured: true,
    tags: ['ergonomic', 'office', 'chair'],
  },
  {
    id: '14',
    name: 'Indoor Plant Set',
    description: 'Curated set of 3 low-maintenance indoor plants in designer ceramic pots. Perfect for brightening up any space.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&h=500&fit=crop',
    category: 'home',
    rating: 4.6,
    reviews: 890,
    inStock: true,
    tags: ['plants', 'indoor', 'decor'],
  },
  {
    id: '15',
    name: 'Minimalist Desk Lamp',
    description: 'Sleek LED desk lamp with adjustable brightness, color temperature control, and USB charging port. Modern Scandinavian design.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=500&h=500&fit=crop',
    category: 'home',
    rating: 4.4,
    reviews: 1567,
    inStock: false,
    tags: ['lamp', 'led', 'minimalist'],
  },
  {
    id: '16',
    name: 'Yoga Mat Premium',
    description: 'Extra-thick, non-slip yoga mat made from eco-friendly natural rubber. Features alignment markers and carrying strap.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop',
    category: 'sports',
    rating: 4.7,
    reviews: 3421,
    inStock: true,
    tags: ['yoga', 'fitness', 'eco-friendly'],
  },
  {
    id: '17',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells ranging from 5-52.5 lbs each. Quick-change mechanism for seamless weight transitions.',
    price: 349.99,
    originalPrice: 449.99,
    image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8c56?w=500&h=500&fit=crop',
    category: 'sports',
    rating: 4.8,
    reviews: 1654,
    inStock: true,
    tags: ['dumbbells', 'weights', 'home-gym'],
  },
  {
    id: '18',
    name: 'Mountain Bike Helmet',
    description: 'Lightweight yet durable helmet with MIPS protection system, adjustable visor, and superior ventilation for trail riding.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1557803175-2f23c1651e39?w=500&h=500&fit=crop',
    category: 'sports',
    rating: 4.6,
    reviews: 876,
    inStock: true,
    tags: ['helmet', 'cycling', 'safety'],
  },
  {
    id: '19',
    name: 'Resistance Bands Set',
    description: 'Complete set of 5 resistance bands with different tension levels. Includes door anchor, handles, and ankle straps.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500&h=500&fit=crop',
    category: 'sports',
    rating: 4.5,
    reviews: 4532,
    inStock: true,
    tags: ['resistance', 'bands', 'workout'],
  },
  {
    id: '20',
    name: 'Bestseller Novel Collection',
    description: 'Curated collection of 5 award-winning novels from contemporary authors. Beautifully bound hardcover editions.',
    price: 89.99,
    originalPrice: 124.99,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&h=500&fit=crop',
    category: 'books',
    rating: 4.9,
    reviews: 1234,
    inStock: true,
    tags: ['novels', 'fiction', 'collection'],
  },
  {
    id: '21',
    name: 'Programming Masterclass',
    description: 'Comprehensive guide to modern software development. Covers React, Node.js, and cloud architecture with practical projects.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=500&fit=crop',
    category: 'books',
    rating: 4.7,
    reviews: 2876,
    inStock: true,
    tags: ['programming', 'tech', 'learning'],
  },
  {
    id: '22',
    name: 'Art & Design Coffee Table Book',
    description: 'Stunning visual journey through modern art and design. 300+ full-color photographs with insightful commentary.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop',
    category: 'books',
    rating: 4.6,
    reviews: 543,
    inStock: true,
    tags: ['art', 'design', 'photography'],
  },
  {
    id: '23',
    name: 'Luxury Skincare Set',
    description: 'Complete skincare routine with cleanser, toner, serum, and moisturizer. Made with organic ingredients and no parabens.',
    price: 149.99,
    originalPrice: 199.99,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop',
    category: 'beauty',
    rating: 4.8,
    reviews: 1987,
    inStock: true,
    featured: true,
    tags: ['skincare', 'organic', 'luxury'],
  },
  {
    id: '24',
    name: 'Professional Hair Dryer',
    description: 'Salon-quality hair dryer with ionic technology, multiple heat settings, and lightweight ergonomic design.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54f4e2588?w=500&h=500&fit=crop',
    category: 'beauty',
    rating: 4.5,
    reviews: 1432,
    inStock: true,
    tags: ['hairdryer', 'salon', 'styling'],
  },
  {
    id: '25',
    name: 'Natural Perfume Collection',
    description: 'Set of 4 artisanal perfumes crafted from natural essences. Features unique seasonal scents in elegant bottles.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500&h=500&fit=crop',
    category: 'beauty',
    rating: 4.7,
    reviews: 876,
    inStock: true,
    tags: ['perfume', 'natural', 'luxury'],
  },
];

export const sampleOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: '1',
    userName: 'John Doe',
    items: [
      { product: products[0], quantity: 1 },
      { product: products[2], quantity: 2 },
    ],
    total: 659.97,
    status: 'delivered',
    date: '2024-01-15',
    shippingAddress: {
      fullName: 'John Doe',
      address: '123 Main St',
      city: 'New York',
      state: 'NY',
      zip: '10001',
      country: 'US',
    },
    paymentMethod: 'Visa ending in 4242',
  },
  {
    id: 'ORD-002',
    userId: '2',
    userName: 'Jane Smith',
    items: [
      { product: products[6], quantity: 1 },
      { product: products[8], quantity: 1 },
    ],
    total: 289.98,
    status: 'shipped',
    date: '2024-01-18',
    shippingAddress: {
      fullName: 'Jane Smith',
      address: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90001',
      country: 'US',
    },
    paymentMethod: 'Mastercard ending in 5555',
  },
  {
    id: 'ORD-003',
    userId: '3',
    userName: 'Bob Wilson',
    items: [
      { product: products[12], quantity: 1 },
    ],
    total: 549.99,
    status: 'processing',
    date: '2024-01-20',
    shippingAddress: {
      fullName: 'Bob Wilson',
      address: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      country: 'US',
    },
    paymentMethod: 'Visa ending in 1234',
  },
  {
    id: 'ORD-004',
    userId: '1',
    userName: 'John Doe',
    items: [
      { product: products[16], quantity: 1 },
      { product: products[18], quantity: 2 },
    ],
    total: 119.97,
    status: 'pending',
    date: '2024-01-22',
    shippingAddress: {
      fullName: 'John Doe',
      address: '123 Main St',
      city: 'New York',
      state: 'NY',
      zip: '10001',
      country: 'US',
    },
    paymentMethod: 'PayPal',
  },
  {
    id: 'ORD-005',
    userId: '4',
    userName: 'Alice Johnson',
    items: [
      { product: products[22], quantity: 1 },
      { product: products[24], quantity: 1 },
    ],
    total: 279.98,
    status: 'delivered',
    date: '2024-01-10',
    shippingAddress: {
      fullName: 'Alice Johnson',
      address: '321 Elm St',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
      country: 'US',
    },
    paymentMethod: 'Visa ending in 9876',
  },
];
